version: "2.4"
services:
  app:
    # image: quay.io/remram44/taguette
    build: .
    # command: ["server", "/config.py"]
    # ports: ["127.0.0.1:7465:7465"]
    environment:
    - APP_ID=pgb_share_to_shortcut.pulipuli.info
    - APP_NAME=Share To Shortcut
    tty: true
    volumes:
      - "./app:/app"
      - "./output:/output"
